# Cross-compilation toolchain for RISC-V 64-bit using Clang 13
SET(CMAKE_SYSTEM_NAME Linux)
SET(CMAKE_SYSTEM_VERSION 1)
SET(CMAKE_SYSTEM_PROCESSOR riscv64)

SET(CMAKE_C_COMPILER $ENV{LLVM_INSTALL}/bin/clang-13)
SET(CMAKE_CXX_COMPILER $ENV{LLVM_INSTALL}/bin/clang++-13)

SET(CMAKE_C_COMPILER_TARGET riscv64-unknown-linux-gnu)
SET(CMAKE_CXX_COMPILER_TARGET riscv64-unknown-linux-gnu)

SET(CMAKE_FIND_ROOT_PATH $ENV{SYSROOT})

SET(CMAKE_FIND_ROOT_PATH_MODE_PROGRAM NEVER)
SET(CMAKE_FIND_ROOT_PATH_MODE_LIBRARY ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_INCLUDE ONLY)
SET(CMAKE_FIND_ROOT_PATH_MODE_PACKAGE ONLY)

# Use ld.lld for linking (avoids missing GCC cross-linker)
SET(CMAKE_EXE_LINKER_FLAGS "-fuse-ld=lld-13")
SET(CMAKE_SHARED_LINKER_FLAGS "-fuse-ld=lld-13")
