"""RV64M extension instruction register flow definitions."""

from __future__ import annotations

from dfg.instruction import ISARegistry, InstructionFormat, RegisterFlow


# RV64M instructions (auto-generated by gen_isadesc.py)
ALL_RV64M: list[tuple[str, RegisterFlow]] = [
    ("mul", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x33, funct3=0x00, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("mulh", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x33, funct3=0x01, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("mulhsu", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x33, funct3=0x02, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("mulhu", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x33, funct3=0x03, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("div", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x33, funct3=0x04, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("divu", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x33, funct3=0x05, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("divuw", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x3b, funct3=0x05, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("divw", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x3b, funct3=0x04, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("rem", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x33, funct3=0x06, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("remu", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x33, funct3=0x07, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("remuw", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x3b, funct3=0x07, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
    ("remw", RegisterFlow(['rd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='R', opcode=0x3b, funct3=0x06, funct7=0x01, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='integer'))),
]



def build_registry(registry: ISARegistry) -> None:
    """Register all RV64M instructions into the given ISA registry."""
    registry.load_extension("M", ALL_RV64M)

