"""RV64M extension instruction register flow definitions."""

from __future__ import annotations

from dfg.instruction import ISARegistry, RegisterFlow


# RV64M instructions (auto-generated by gen_isadesc.py)
ALL_RV64M: list[tuple[str, RegisterFlow]] = [
    ("div", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("divu", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("divuw", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("divw", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("mul", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("mulh", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("mulhsu", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("mulhu", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("mulw", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("rem", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("remu", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("remuw", RegisterFlow(['rd'], ['rs1', 'rs2'])),
    ("remw", RegisterFlow(['rd'], ['rs1', 'rs2'])),
]



def build_registry(registry: ISARegistry) -> None:
    """Register all RV64M instructions into the given ISA registry."""
    registry.load_extension("M", ALL_RV64M)

