"""RV64F extension instruction register flow definitions."""

from __future__ import annotations

from dfg.instruction import ISARegistry, RegisterFlow


# RV64F instructions (auto-generated by gen_isadesc.py)
ALL_RV64F: list[tuple[str, RegisterFlow]] = [
    ("c.flw", RegisterFlow(['frd'], ['rs1'])),
    ("c.flwsp", RegisterFlow(['frd'], ['rs1'])),
    ("c.fsw", RegisterFlow([], ['frs2', 'rs1'])),
    ("c.fswsp", RegisterFlow([], ['frs2', 'rs1'])),
    ("fadd.s", RegisterFlow(['frd'], ['frs1', 'frs2'])),
    ("fclass.s", RegisterFlow(['rd'], ['frs1'])),
    ("fcvt.lu.s", RegisterFlow(['rd'], ['frs1'])),
    ("fcvt.l.s", RegisterFlow(['rd'], ['frs1'])),
    ("fcvt.s.l", RegisterFlow(['frd'], ['rs1'])),
    ("fcvt.s.lu", RegisterFlow(['frd'], ['rs1'])),
    ("fcvt.s.w", RegisterFlow(['frd'], ['rs1'])),
    ("fcvt.s.wu", RegisterFlow(['frd'], ['rs1'])),
    ("fcvt.wu.s", RegisterFlow(['rd'], ['frs1'])),
    ("fcvt.w.s", RegisterFlow(['rd'], ['frs1'])),
    ("fdiv.s", RegisterFlow(['frd'], ['frs1', 'frs2'])),
    ("feq.s", RegisterFlow(['rd'], ['frs1', 'frs2'])),
    ("fle.s", RegisterFlow(['rd'], ['frs1', 'frs2'])),
    ("flrw", RegisterFlow(['frd'], ['rs1', 'rs2'])),
    ("flt.s", RegisterFlow(['rd'], ['frs1', 'frs2'])),
    ("flurw", RegisterFlow(['frd'], ['rs1', 'rs2'])),
    ("flw", RegisterFlow(['frd'], ['rs1'])),
    ("fmadd.s", RegisterFlow(['frd'], ['frs1', 'frs2', 'frs3'])),
    ("fmax.s", RegisterFlow(['frd'], ['frs1', 'frs2'])),
    ("fmin.s", RegisterFlow(['frd'], ['frs1', 'frs2'])),
    ("fmsub.s", RegisterFlow(['frd'], ['frs1', 'frs2', 'frs3'])),
    ("fmul.s", RegisterFlow(['frd'], ['frs1', 'frs2'])),
    ("fmv.s.x", RegisterFlow(['frd'], ['rs1'])),
    ("fmv.x.s", RegisterFlow(['rd'], ['frs1'])),
    ("fnmadd.s", RegisterFlow(['frd'], ['frs1', 'frs2', 'frs3'])),
    ("fnmsub.s", RegisterFlow(['frd'], ['frs1', 'frs2', 'frs3'])),
    ("fsgnjn.s", RegisterFlow(['frd'], ['frs1', 'frs2'])),
    ("fsgnjx.s", RegisterFlow(['frd'], ['frs1', 'frs2'])),
    ("fsgnj.s", RegisterFlow(['frd'], ['frs1', 'frs2'])),
    ("fsqrt.s", RegisterFlow(['frd'], ['frs1'])),
    ("fsrw.th", RegisterFlow([], ['frd', 'rs1', 'rs2'])),
    ("fsub.s", RegisterFlow(['frd'], ['frs1', 'frs2'])),
    ("fsurw", RegisterFlow([], ['frd', 'rs1', 'rs2'])),
    ("fsw", RegisterFlow([], ['frs2', 'rs1'])),
    ("vfmv.f.s", RegisterFlow(['frd'], [])),
    ("vfmv.s.f", RegisterFlow([], ['frs1'])),
]



def build_registry(registry: ISARegistry) -> None:
    """Register all RV64F instructions into the given ISA registry."""
    registry.load_extension("F", ALL_RV64F)

