"""RV64F extension instruction register flow definitions."""

from __future__ import annotations

from dfg.instruction import ISARegistry, InstructionFormat, RegisterFlow


# RV64F instructions (auto-generated by gen_isadesc.py)
ALL_RV64F: list[tuple[str, RegisterFlow]] = [
    ("c.flw", RegisterFlow(['frd'], [], encoding=InstructionFormat(format_type='R', opcode=0x00, funct3=None, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("c.flwsp", RegisterFlow(['frd'], [], encoding=InstructionFormat(format_type='R', opcode=0x00, funct3=None, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("c.fsw", RegisterFlow([], ['frs2'], encoding=InstructionFormat(format_type='R', opcode=0x00, funct3=None, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("c.fswsp", RegisterFlow([], ['frs2'], encoding=InstructionFormat(format_type='R', opcode=0x00, funct3=None, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fadd.s", RegisterFlow(['frd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x00, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fclass.s", RegisterFlow(['rd'], ['frs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x01, funct7=0x70, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fcvt.lu.s", RegisterFlow(['rd'], ['frs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x60, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fcvt.l.s", RegisterFlow(['rd'], ['frs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x60, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fcvt.s.l", RegisterFlow(['frd'], ['rs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x68, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fcvt.s.lu", RegisterFlow(['frd'], ['rs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x68, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fcvt.s.w", RegisterFlow(['frd'], ['rs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x68, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fcvt.s.wu", RegisterFlow(['frd'], ['rs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x68, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fcvt.wu.s", RegisterFlow(['rd'], ['frs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x60, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fcvt.w.s", RegisterFlow(['rd'], ['frs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x60, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fdiv.s", RegisterFlow(['frd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x0c, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("feq.s", RegisterFlow(['rd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x02, funct7=0x50, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fle.s", RegisterFlow(['rd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x00, funct7=0x50, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("flt.s", RegisterFlow(['rd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x01, funct7=0x50, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("flw", RegisterFlow(['frd'], ['rs1'], encoding=InstructionFormat(format_type='I', opcode=0x07, funct3=0x02, funct7=None, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=True, may_store=False, reg_class='float'))),
    ("fmadd.s", RegisterFlow(['frd'], ['frs1', 'frs2', 'frs3'], encoding=InstructionFormat(format_type='R4', opcode=0x43, funct3=None, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=True, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fmax.s", RegisterFlow(['frd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x01, funct7=0x14, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fmin.s", RegisterFlow(['frd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x00, funct7=0x14, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fmsub.s", RegisterFlow(['frd'], ['frs1', 'frs2', 'frs3'], encoding=InstructionFormat(format_type='R4', opcode=0x47, funct3=None, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=True, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fmul.s", RegisterFlow(['frd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x08, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fmv.s.x", RegisterFlow(['frd'], ['rs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x00, funct7=0x78, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fmv.x.s", RegisterFlow(['rd'], ['frs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x00, funct7=0x70, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fnmadd.s", RegisterFlow(['frd'], ['frs1', 'frs2', 'frs3'], encoding=InstructionFormat(format_type='R4', opcode=0x4f, funct3=None, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=True, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fnmsub.s", RegisterFlow(['frd'], ['frs1', 'frs2', 'frs3'], encoding=InstructionFormat(format_type='R4', opcode=0x4b, funct3=None, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=True, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fsgnjn.s", RegisterFlow(['frd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x01, funct7=0x10, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fsgnjx.s", RegisterFlow(['frd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x02, funct7=0x10, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fsgnj.s", RegisterFlow(['frd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=0x00, funct7=0x10, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fsqrt.s", RegisterFlow(['frd'], ['frs1'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x2c, has_rd=True, has_rs1=True, has_rs2=False, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=False, reg_class='float'))),
    ("fsub.s", RegisterFlow(['frd'], ['frs1', 'frs2'], encoding=InstructionFormat(format_type='R', opcode=0x53, funct3=None, funct7=0x04, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=False, imm_bits=0, may_load=False, may_store=False, reg_class='float'))),
    ("fsw", RegisterFlow([], ['frs2', 'rs1'], encoding=InstructionFormat(format_type='S', opcode=0x27, funct3=0x02, funct7=None, has_rd=False, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=True, reg_class='float'))),
    ("th.flrw", RegisterFlow(['frd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='I', opcode=0x0b, funct3=0x06, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=True, imm_bits=12, may_load=True, may_store=False, reg_class='float'))),
    ("th.flurw", RegisterFlow(['frd'], ['rs1', 'rs2'], encoding=InstructionFormat(format_type='I', opcode=0x0b, funct3=0x06, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=True, imm_bits=12, may_load=True, may_store=False, reg_class='float'))),
    ("th.fsrw", RegisterFlow([], ['frd', 'rs1', 'rs2'], encoding=InstructionFormat(format_type='S', opcode=0x0b, funct3=0x07, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=True, reg_class='float'))),
    ("th.fsurw", RegisterFlow([], ['frd', 'rs1', 'rs2'], encoding=InstructionFormat(format_type='S', opcode=0x0b, funct3=0x07, funct7=None, has_rd=True, has_rs1=True, has_rs2=True, has_rs3=False, has_imm=True, imm_bits=12, may_load=False, may_store=True, reg_class='float'))),
]



def build_registry(registry: ISARegistry) -> None:
    """Register all RV64F instructions into the given ISA registry."""
    registry.load_extension("F", ALL_RV64F)

